name: "first workflow"
on: 
  push:
  pull_request:
    branches:
      - main

jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      -  name: Get Repository Code
         uses: actions/checkout@v4
         with: 
          node-version: 24

      - name: Install Dependency
        run: npm ci

      - name: React Build
        run: npm run build